### ISSUE TITLE
Setup defaults CNI, locations, ...? 

### ISSUE THREAD

**Issue by codeagencybe** [StarpTech/k-andy#10]
Hello

Let me first say an huge thank you for this amazing project and repo. This is unbelievable. 
I was searching for any good resources on k3s and Hetzner and could not believe some hidden gem like this existed. 
This repo deserves way more stars and credit than it has. 

That said, I was wondering which CNI is now the default one? 
I was reading through some of the very few other issues and read something about flannel being changed and somebody mentioned CILIUM but I don't know if that is already the case now? 
Or is there an option to choose for one of the many default CNI's that K3s offers? 

I also see there is an option for using multiple locations which I like a lot. 
But is this the default or do I need to set a flag somewhere to initiate using all 3 datacenter locations from Hetzner? 

Can the load balancer handle just 1 application/workload? Or can I use it to host to multiple applications? 
Ideally, I want to use this to host a dozen of Wordpress websites as high available so they can recover fast or even better stay online even when there is node failure. 
My goal is to launch 3 masters and minimum 6 agents, all CPX51 machines. 

Thanks for feedback!
Fabio

**Comment by toabi** [comment]
The CNI is still flannel.

In https://github.com/StarpTech/k-andy/pull/12/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR19 I added wireguard as backend because of https://docs.hetzner.com/cloud/networks/faq/#is-traffic-inside-hetzner-cloud-networks-encrypted

There is recent fork which added cilium: https://github.com/mysticaltech/kube-hetzner - but it forked before adding agent-groups and other small features here.

I personally built an ingress tf module which installs ingress-nginx as DaemonSet on NodePorts and can provision Hetzner LoadBalancers in the zones I want which forward to those. So far that works well.

**Comment by toabi** [comment]
Ah, jeah and the locations default to Nürnberg, Falkenstein and Helsinki. There will be a control-plane node in each of them and workers will be distributed in all of them too.

Beware that HetznerVolumes store is bound to to the Zone, so if a pod creates a volume in nbg1 it can only be mounted by a pod which runs on a worker on a node in nbg1.

Running a replicating ceph layer with https://rook.io/docs/rook/v1.7/ could be used as a solution for that.

**Comment by StarpTech** [comment]
I think the question was answered. Feel free to reopen.
