### ISSUE TITLE
Request. how to use my own domain in a deployment?

### ISSUE THREAD

**Issue by 1mfaasj** [StarpTech/k-andy#14]
Hi

Thanks for this repo and for the 'hello-kubernetes.yaml' example!
This works in my case, but to understand it even better, could you maybe make an example in which you can use your own domain and make it work on https?
so instead of http://localhost:8080 (at hello-kubernetes) I would like to use https://hellokuber.mydomain.com for instance. or at least using cnames.

if it's not too much to ask!

I understand that Traefik is been disabled, is there a reason for that? and which ingress controller is used now?
if you can make a yaml (deployment) example how I can achieve this with Traefik or another ingress controller. I am very grateful to you

I think that I can achieve it with the cloud-controller-manager, but Iam not 100%
and to add some labels in the deployment? but what exactly idk:
  service:
    annotations:

**Comment by toabi** [comment]
The reason is, that this stack should be just the base of a kubernetes cluster.

You can install any ingress-controller you want on top of it with any tooling you might like. I personally have nginx-ingress running on NodePorts and manually provision Hetzner LoadBalancers in front of it.

But theoretically you can just install the ingress-nginx helm chart with service.type = "LoadBalancer" and when your DNS points to the LBs and you have an Ingress object it'll work.

**Comment by StarpTech** [comment]
I think the question was answered. Feel free to reopen.
